name: Deploy to runnerjardin

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - self-hosted
      - jardin-site

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Deploy Backend
        run: |
          cd back
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_JARDIN }}" >> .env
          composer install
          php bin/console doctrine:database:create
          php bin/console doctrine:schema:update --force
          php bin/console lexik:jwt:generate-keypair
      - name: Build and Deploy Frontend
        run: |
          cd front
          yarn install
          echo "REACT_APP_API_BASE_URL=http://activite-jardin-api.duckdns.org/api/" >> .env 
          npm run build
          # deploy frontend code to server
