name: Deploy to runnerjardin

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - self-hosted
      - jardin-site

    steps:
      - name: save public/images
        run: |
          cp -r back/public/images /var/www/backup/images
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Deploy Backend
        run: |
          chmod 777 -R back
          cd back
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_JARDIN }}" >> .env
          composer install
          php bin/console doctrine:schema:update --force
          php bin/console lexik:jwt:generate-keypair
          cd public
          chmod 777 images
      - name: restore public/images
        run: |
          cp -r /var/www/backup/images back/public/
      - name: Build and Deploy Frontend
        run: |
          cd front
          yarn install
          echo "REACT_APP_API_BASE_URL=https://www.activite-jardin-api.duckdns.org/api/" >> .env 
          npm run build
          # deploy frontend code to server
